# Generated by Django 5.1.2 on 2024-10-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_remove_producto_cantidad_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
